name: navigation_service
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  navigation_domain:
    path: ../../domain/navigation_domain
  riverpod: ^2.3.0
  flutter_riverpod: ^2.3.0
  riverpod_annotation: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  riverpod_generator: ^2.0.0

flutter:

